{
 "title": "Garmin Connect",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Steps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (\"steps\") AS \"Steps\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"distance\" AS \"Distance\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Resting Heart Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"rhr\" AS \"Resting Heart Rate\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Respiration Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"rr_waking_avg\" AS \"Resting Heart Rate\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Stress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"stress_avg\" AS \"Resting Heart Rate\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Calories",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"calories_total\" AS \"Resting Heart Rate\" FROM \"Daily Summary\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Stress",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"Garmin Connect\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"stress\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      date: r._time,  // Extract YYYY-MM-DD\r\n      stress: r._value\r\n  }))\r\n  |> keep(columns: [\"date\", \"stress\"]) // Keeps only selected columns\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"Garmin Connect\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heart_rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      date: r._time,  // Extract YYYY-MM-DD\r\n      hr: r._value\r\n  }))\r\n  |> keep(columns: [\"date\", \"hr\"]) // Keeps only selected columns\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Body Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT \"bb_charged\" AS \" Charged Body Battery\", \"bb_min\" AS \"Min Body Battery\", \"bb_max\" AS \" Max Body Battery\" FROM \"Daily Summary\" WHERE $timeFilter "
    }
   ]
  },
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "SELECT \"steps\" FROM \"Monitoring\" WHERE $timeFilter  fill(null)"
    }
   ]
  }
 ]
}