{
 "title": "PostgreSQL Metrics",
 "description": "Sample dashboard of Databases PostgreSQL",
 "tags": [ "postgresql" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource_name",
    "label": "cluster_id",
    "query": "SHOW TAG VALUES FROM \"postgresql\" WITH KEY = \"resource_name\""
   },
   {
    "name": "node",
    "label": "node",
    "query": "SHOW TAG VALUES FROM \"postgresql\" WITH KEY = \"host\" WHERE resource_name =~ /$resource_name/ AND host !~ /restore.*/  AND time > now() -1h AND time < now() LIMIT 100"
   },
   {
    "name": "db",
    "label": "database",
    "query": "SHOW TAG VALUES FROM \"postgresql\" WITH KEY = \"db\" WHERE resource_name =~ /$resource_name/ LIMIT 100"
   },
   { "name": "filters", "label": "Optional filters" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Disk usage of /data in percentage.",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"used_percent\") FROM \"disk\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"path\" = '/') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage in percentage.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Inbound traffic",
   "type": "stat",
   "description": "Sum of all the inbound traffic over the time range.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(non_negative_derivative) FROM (SELECT non_negative_derivative(sum(\"bytes_recv\"), $__interval) FROM \"net\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"interface\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outbound traffic",
   "type": "stat",
   "description": "Sum of all the outbound traffic over the time range.",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(non_negative_derivative) FROM (SELECT non_negative_derivative(sum(\"bytes_sent\"), $__interval) FROM \"net\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"interface\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"usage_system\") + mean(\"usage_user\") FROM \"cpu\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "received",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks & conflicts",
   "type": "timeseries",
   "description": "Number of deadlocks and conflicts per database.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "conflicts - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    },
    {
     "alias": "deadlocks - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples/minute (fetched,inserted,updated,deleted)",
   "type": "timeseries",
   "description": "Rate per minute of fetched,inserted,updated and deleted tuples.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"tup_fetched\"), 1m) FROM \"postgresql\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($__interval), \"db\" fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    },
    {
     "alias": "inserted - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"tup_inserted\"), 1m) FROM \"postgresql\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($__interval), \"db\" fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    },
    {
     "alias": "updated - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"tup_updated\"), 1m) FROM \"postgresql\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($__interval), \"db\" fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    },
    {
     "alias": "deleted - $tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(mean(\"tup_deleted\"), 1m) FROM \"postgresql\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($__interval), \"db\" fill(null)",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "connections / database",
   "type": "timeseries",
   "description": "Number of connection per database.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_db - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  },
  {
   "title": "Average transactions / second",
   "type": "timeseries",
   "description": "Average transactions per second (xact_commit).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "tps - $tag_host/$tag_db",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "query": "SELECT non_negative_derivative(max(\"xact_commit\"), 1s) FROM \"postgresql\" WHERE (\"resource_name\" =~ /^$resource_name$/ AND \"host\" =~ /^$node$/ AND \"db\" =~ /^$db$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\" fill(null)",
     "select": [
      [
       { "params": [ "numb" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "resource_name", "operator": "=~", "value": "/^$resource_name$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$db$/" }
     ]
    }
   ]
  }
 ]
}